// The fleet `tarmac serve --demo` shows, and the two promises it ships with.
//
// A demo is a screenshot with a server behind it, and both ways it can go wrong are quiet.
// It can start reading the machine it runs on — at which point a capture carries somebody's
// working directories out of their home — and it can stop looking like demo data, at which
// point a screenshot of an invented fleet is passed around as a real one. So the invented
// fleet is generated by code, this file is what that code is held to, and the two end-to-end
// checks at the bottom run the real binary with no `claude` on the machine and nothing in the
// snapshot directory: a demo that had learnt to derive from the live sources would answer an
// empty fleet there, and every unit check above would stay green.

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import type { ChildProcess } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { DEMO_HOME, DEMO_MINUTES, DEMO_SESSIONS, demoCollector, demoDayStart, demoFleetAt, demoHistory } from '../src/demo.ts';
import { parseArgs } from '../src/args.ts';
import { HISTORY_SLOTS } from '../src/history.ts';
import { stateOf } from '../src/map.ts';
import { renderPage } from '../src/render.ts';
import { DEFAULT_STALE_AFTER_MS } from '../src/config.ts';
import { rawGetText, waitForOutput } from './bounded.ts';
import { tempDir } from './sandbox.ts';

/** A GET on a loopback Host, with the answer's body kept — every request below is one. */
async function get(port: number, path: string): Promise<string> {
  const answer = await rawGetText(String(port), '127.0.0.1', path);
  assert.equal(answer.status, 200, `${path} answered ${answer.status}: ${answer.body}`);
  return answer.body;
}

const CLI = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'cli.ts');

/** A day anchored anywhere: the demo takes its clock as an argument, so this one is pinned. */
const DAY_START = 1786600000000;
/** The minute every capture is taken of — the one the live view always shows. */
const SHOWN = DEMO_MINUTES - 1;

// ── the red line ──────────────────────────────────────────────────────────────────────────

// `os.homedir()` is the one string that proves a capture was taken of the machine that took
// it, and it is the one a demo may never publish. Held positively, by prefix, rather than
// against a list of names the maintainer's own fleet uses: a denylist in a public test file
// would publish exactly the names it exists to keep out of a screenshot.
test('nothing the demo fleet shows comes off the machine that runs it', () => {
  assert.equal(DEMO_HOME, '/Users/jane');
  const home = os.homedir();
  // Vacuous wherever the demo home is nowhere near the real one — every CI runner — and it
  // accuses the invented home on a machine whose home is `/Users` or is not set at all. The
  // prefix check below is what actually holds every path; this is the loud one.
  const meaningful = home.length > 1 && !`${DEMO_HOME}/`.startsWith(`${home}/`);
  for (const minute of [0, 1, 400, 812, SHOWN]) {
    const fleet = demoFleetAt(minute, DAY_START);
    if (meaningful) {
      assert.equal(JSON.stringify(fleet).includes(home), false, `minute ${minute} carries this machine's home directory`);
    }
    for (const r of fleet.rows) {
      assert.equal(typeof r.cwd, 'string');
      assert.ok(r.cwd!.startsWith(`${DEMO_HOME}/`), `minute ${minute}: cwd outside the demo home — ${r.cwd}`);
    }
  }
});

// ── the fleet itself ──────────────────────────────────────────────────────────────────────

test('the minute every capture is taken of is eight sessions', () => {
  assert.equal(DEMO_SESSIONS, 8);
  assert.equal(demoFleetAt(SHOWN, DAY_START).rows.length, DEMO_SESSIONS);
});

// The words this product exists to tell apart. A demo showing three of them sells three, and
// the one it would drop is the expensive one: `unknown` is the whole claim that tarmac says "I
// cannot read this" where everything else says "calm". Spelled out rather than derived, so a
// vocabulary that gains a word lands here as a failure to look at.
test('the shown minute puts a session in every state the map can draw, and the waiting one says why', () => {
  const fleet = demoFleetAt(SHOWN, DAY_START);
  const states = new Set(fleet.rows.map(stateOf));
  assert.deepEqual([...states].sort(), ['busy', 'idle', 'unknown', 'waiting']);
  const waiting = fleet.rows.filter((r) => stateOf(r) === 'waiting');
  assert.equal(waiting.length, 1);
  assert.equal(waiting[0].waitingFor, 'permission prompt');
});

// A `!` on a demo is a reading the reader is told not to trust, and one that appeared because
// the invented ages drifted is a mark the fleet never earned.
test('no reading in the shown minute is stale, and every session is chained', () => {
  const { rows, health } = demoFleetAt(SHOWN, DAY_START);
  assert.equal(health.stale, 0);
  for (const r of rows) {
    assert.ok(r.snapshotAgeMs !== null && r.snapshotAgeMs < DEFAULT_STALE_AFTER_MS, `${r.project} is dated`);
  }
  assert.equal(health.covered, health.sessions, 'every session chained: no coverage banner');
  assert.equal(health.drift, 0);
  assert.equal(health.schemaBroken, false);
  assert.equal(health.noSessionId, 0);
  assert.equal(health.schemaGuard.state, 'ok', 'a Claude Code build the fixtures cover: no shape-check footnote');
  assert.equal(health.unknownStatus, 1, 'the one unrecognised status the demo means to show, and only one');
});

// A demo whose picture moved between two runs would be a screenshot nobody could re-take, and
// a README whose captures disagree with the tool that made them.
test('the same minute of the invented day renders the same fleet every time', () => {
  for (const minute of [0, 300, 900, SHOWN]) {
    assert.deepEqual(demoFleetAt(minute, DAY_START), demoFleetAt(minute, DAY_START), `minute ${minute} moved between two reads`);
  }
});

// A day that is the same fleet at every minute is a scrubber with nothing behind it, and the
// flat charts #150 exists to replace.
test('the invented day has waves in it: sessions arrive, and what they are doing moves', () => {
  const counts = new Set<number>();
  const shapes = new Set<string>();
  const busy = new Set<number>();
  for (let m = 0; m < DEMO_MINUTES; m += 7) {
    const { rows, health } = demoFleetAt(m, DAY_START);
    counts.add(rows.length);
    busy.add(health.busy);
    shapes.add(rows.map((r) => `${r.name}:${stateOf(r)}`).sort().join(' '));
  }
  assert.ok(counts.size > 1, `the same ${[...counts][0]} sessions all day`);
  assert.ok(busy.size > 2, `the fleet is ${busy.size} distinct busy count(s) all day — a flat chart`);
  assert.ok(shapes.size >= 8, `the whole day is ${shapes.size} distinct fleet(s)`);
});

// The scrubber walks minutes, not sessions, so a minute with nobody in it is a frame of empty
// map with no explanation on it.
test('no minute of the invented day is an empty fleet', () => {
  for (let m = 0; m < DEMO_MINUTES; m++) {
    assert.ok(demoFleetAt(m, DAY_START).rows.length > 0, `minute ${m} has no sessions at all`);
  }
});

// The state this project exists to get right: the key present, holding null — a session that
// has taken no turn since it was recycled, which is not a session at zero.
test('the day walks past a session that has taken no turn yet, and it is not a zero', () => {
  const seen: number[] = [];
  for (let m = 0; m < DEMO_MINUTES; m++) {
    for (const r of demoFleetAt(m, DAY_START).rows) {
      if (r.ctxState === 'fresh') {
        assert.equal(r.ctxPct, null, `minute ${m} reports a percentage for an unmeasured window`);
        seen.push(m);
      }
    }
  }
  assert.ok(seen.length > 0, 'no minute of the day has a session that has taken no turn');
});

// ── the record behind the scrubber ────────────────────────────────────────────────────────

// At 1440 exactly nothing has aged out, `dropped` stays false, and `since` reverts to the
// moment the ring was made — a day AFTER the oldest sample it is serving. The record would
// then be lying in the one sentence the page quotes it for.
test('the demo plays one minute more than the ring keeps, so the record dates itself by its own oldest slot', () => {
  assert.equal(DEMO_MINUTES, HISTORY_SLOTS + 1);
  const record = demoHistory(DAY_START).read();
  assert.equal(record.samples.length, HISTORY_SLOTS);
  assert.equal(record.missed, 0, 'a seeded record with holes in it would draw gaps the fleet never had');
  assert.equal(record.since, DAY_START + 60_000, 'the record dates itself by the oldest slot it still holds');
});

// The record is the same reduction of the same fleets the live view is built from — not a
// second account of the invented day, kept in step by hand.
test('the last sample in the record is the minute the live view shows', () => {
  const record = demoHistory(DAY_START).read();
  const newest = record.samples[record.samples.length - 1];
  assert.equal(newest.t, DAY_START + SHOWN * 60_000);
  assert.equal(newest.sessions.length, DEMO_SESSIONS);
});

// ── the live view is frozen on the last minute ────────────────────────────────────────────

// Two captures taken an hour apart have to be the same picture, so the collector does not walk
// the day: it answers the last minute of it, dated by the clock that asked.
test('the collector answers the shown minute whatever the clock says, dated by that clock', async () => {
  let clock = DAY_START + SHOWN * 60_000;
  const collect = demoCollector(DAY_START, () => clock);
  const first = await collect();
  clock += 3600_000;
  const later = await collect();
  assert.equal(first.rows.length, DEMO_SESSIONS);
  assert.deepEqual(
    later.rows.map((r) => `${r.name}:${stateOf(r)}:${r.ctxPct}`),
    first.rows.map((r) => `${r.name}:${stateOf(r)}:${r.ctxPct}`),
    'the demo fleet moved on its own between two reads an hour apart',
  );
  assert.equal(later.health.generatedAt, clock, 'the reading is dated by the clock that asked for it');
});

test('the day the collector plays ends now, so its last minute is the fleet being shown', () => {
  const now = 1786600000000;
  assert.equal(demoDayStart(now), now - SHOWN * 60_000);
});

// ── the marker ────────────────────────────────────────────────────────────────────────────

// The whole of the second promise. A screenshot of an invented fleet with nothing on it saying
// so is a screenshot that will be passed around as a real one.
test('the page says it is demo data, and says it in the shell rather than the fragment', () => {
  const fleet = demoFleetAt(SHOWN, DAY_START);
  const page = renderPage(fleet, 'table', { demo: true });
  assert.match(page, /demo data/i, 'nothing on the page says the fleet is invented');
  // In the header, above the fleet: the fragment is swapped on every poll, and a marker that
  // lived there would be a marker a reader can watch disappear.
  const header = page.slice(page.indexOf('<header>'), page.indexOf('</header>'));
  assert.match(header, /demo data/i, 'the marker is not in the header, where it cannot be scrolled past');
});

test('a serve nobody asked for a demo says nothing about demo data', () => {
  const fleet = demoFleetAt(SHOWN, DAY_START);
  assert.equal(/demo data/i.test(renderPage(fleet, 'table')), false);
  assert.equal(/demo data/i.test(renderPage(fleet, 'map', { historyEnabled: true })), false);
});

// ── the parser ────────────────────────────────────────────────────────────────────────────

test('--demo is an option of serve', () => {
  assert.equal(parseArgs(['serve', '--demo']).demo, true);
  assert.equal(parseArgs(['serve']).demo, false);
});

test('--demo is an option of nothing else', () => {
  for (const command of ['list', 'install', 'uninstall']) {
    assert.throws(() => parseArgs([command, '--demo']), /--demo is not an option of `tarmac /, `${command} accepted --demo`);
  }
});

// ── end to end, which is where the first promise is actually held ─────────────────────────

/**
 * `tarmac serve --demo` against a home with no `claude` on it and no snapshot directory in it.
 *
 * That is the whole point of the fixture: every live source is broken, so a demo built on top
 * of one answers an empty fleet — or a 500 — and the assertions below go red. Nothing about
 * the shape of `src/demo.ts` can make this pass on its own.
 */
async function serveDemo(flags: string[] = []): Promise<{ child: ChildProcess; port: number; home: string }> {
  const home = tempDir('tarmac-demo-');
  const child = spawn(
    process.execPath,
    [CLI, 'serve', '--demo', '--port', '0', '--home', home, '--claude-bin', path.join(home, 'no-such-claude'), ...flags],
    { stdio: ['ignore', 'pipe', 'pipe'], env: { ...process.env, TARMAC_PORT: '', XDG_STATE_HOME: '' } },
  );
  const out = await waitForOutput(child, /tarmac serving/);
  const port = Number(out.match(/tarmac serving http:\/\/127\.0\.0\.1:(\d+)/)![1]);
  return { child, port, home };
}

test('serve --demo answers a full fleet with no claude on the machine and no snapshots anywhere', async (t) => {
  const { child, port } = await serveDemo();
  t.after(() => child.kill('SIGKILL'));

  const fleet = JSON.parse(await get(port, '/api/fleet')) as { rows: Array<{ name: string; cwd: string }>; health: { sessions: number; covered: number } };
  assert.equal(fleet.rows.length, DEMO_SESSIONS, 'the demo went through the live sources, which are broken here');
  assert.equal(fleet.health.covered, DEMO_SESSIONS);
  for (const r of fleet.rows) assert.ok(r.cwd.startsWith(`${DEMO_HOME}/`), `a row off this machine: ${r.cwd}`);

  const page = await get(port, '/');
  assert.match(page, /demo data/i, 'the served page does not say it is a demo');
});

// The other half of "nothing on this machine was read": a demo that journals is a demo that
// writes an invented fleet into somebody's real record of their real one.
test('serve --demo writes nothing, journal included, however many days it is asked for', async (t) => {
  const { child, port, home } = await serveDemo(['--history-days', '30']);
  t.after(() => child.kill('SIGKILL'));

  // Asked for, answered, and still nothing on disk: the record it serves is the seeded ring.
  const record = JSON.parse(await get(port, '/api/history')) as { samples: unknown[] };
  assert.ok(record.samples.length >= HISTORY_SLOTS - 1, `the demo served ${record.samples.length} minutes of record`);

  const written = fs.existsSync(home) ? walk(home) : [];
  assert.deepEqual(written, [], `serve --demo wrote ${written.length} file(s) under the home it was pointed at`);
});

/** Every file under a directory, at any depth, relative to it. */
function walk(dir: string, prefix = ''): string[] {
  const out: string[] = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix === '' ? e.name : `${prefix}/${e.name}`;
    if (e.isDirectory()) out.push(...walk(path.join(dir, e.name), rel));
    else out.push(rel);
  }
  return out.sort();
}
