// The fleet behind every pixel in the README, asserted where the pixels cannot be.
//
// A screenshot is the one artefact in this repo nobody can diff. It is checked in, it is the
// first thing a reader sees, and once it is there the only thing standing between it and a
// leaked working directory is whoever last ran the capture. So the fleet it is taken of is
// generated by code, and this file is what that code is held to: synthetic throughout, and
// showing what the README claims it shows.
//
// It reads the demo through the same two joins the product does — `parseAgents` over the
// `agents` array, `extractTelemetry` over each payload — so a demo that drifts out of the
// shapes tarmac actually reads fails here rather than in a screenshot nobody re-takes.

import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import { DEMO_HOME, DEMO_MINUTES, demoMinute } from '../scripts/demo-fleet.ts';
import { parseAgents } from '../src/sessions.ts';
import { extractTelemetry } from '../src/snapshots.ts';
import { buildFleet, busyOnStaleFleet } from '../src/fleet.ts';
import { stateOf } from '../src/map.ts';
import { readLimits } from '../src/limits.ts';
import { DEFAULT_STALE_AFTER_MS } from '../src/config.ts';
import { HISTORY_SLOTS } from '../src/history.ts';
import type { Fleet } from '../src/fleet.ts';
import type { Snapshot } from '../src/snapshots.ts';

/** A day anchored anywhere: the demo takes its clock as an argument, so this one is pinned. */
const DAY_START = 1786600000000;
const at = (minute: number): number => DAY_START + minute * 60_000;

/**
 * The demo's two sources, joined exactly as `collectFleet` joins the real ones — including
 * discovery's own health, which is the third input and the one a shortcut here would drop.
 * Without it `health.noSessionId` and `health.discovered` are computed from the rows alone,
 * and two of the assertions below would be true of any demo at all.
 */
function fleetAt(minute: number): Fleet {
  const { agents, snapshots } = demoMinute(minute, DAY_START);
  const now = at(minute);
  const telemetry = new Map<string, Snapshot>();
  for (const { payload, ageMs } of snapshots) {
    const t = extractTelemetry(payload);
    assert.ok(t.sessionId, 'a demo payload with no session_id would be dropped, silently');
    telemetry.set(t.sessionId, { ...t, ageMs, file: `${t.sessionId}.json` });
  }
  const { sessions, health: discovery } = parseAgents(JSON.stringify(agents));
  return buildFleet({ sessions, snapshots: telemetry, now, discovery });
}

// The red line, mechanised. `os.homedir()` is the one string that proves a capture was taken
// of the machine that took it, and it is the one this repo may never publish.
test('nothing the demo publishes comes off the machine that runs it', () => {
  // The substring check is the loud one and the weaker one: it is vacuous wherever the demo
  // home is nowhere near the real one — every CI runner — and it accuses the fixtures' own
  // standard on a machine whose home is `/Users` or is not set at all. So it runs only where
  // it can mean something, and the prefix check below is what actually holds every path.
  const home = os.homedir();
  const meaningful = home.length > 1 && !`${DEMO_HOME}/`.startsWith(`${home}/`);
  for (const minute of [0, 1, 400, 812, DEMO_MINUTES - 1]) {
    const sources = demoMinute(minute, DAY_START);
    const json = JSON.stringify(sources);
    if (meaningful) {
      assert.equal(json.includes(home), false, `minute ${minute} carries this machine's home directory`);
    }
    for (const a of sources.agents) {
      assert.equal(typeof a.cwd, 'string');
      assert.ok((a.cwd as string).startsWith(`${DEMO_HOME}/`), `minute ${minute}: cwd outside the demo home`);
    }
    for (const { payload } of sources.snapshots) {
      for (const p of paths(payload)) {
        assert.ok(p.startsWith(`${DEMO_HOME}/`), `minute ${minute}: payload path outside the demo home — ${p}`);
      }
    }
  }
});

/** Every absolute path anywhere in a payload, however deep. */
function paths(value: unknown): string[] {
  if (typeof value === 'string') return value.startsWith('/') ? [value] : [];
  if (Array.isArray(value)) return value.flatMap(paths);
  if (value !== null && typeof value === 'object') return Object.values(value).flatMap(paths);
  return [];
}

// What the README's screenshots are captioned as showing. A demo that quietly stopped
// producing one of the four would leave the caption lying with nothing red anywhere.
test('the minute the screenshots are taken of shows all four states, and the waiting one says why', () => {
  const fleet = fleetAt(DEMO_MINUTES - 1);
  const states = new Set(fleet.rows.map(stateOf));
  assert.deepEqual([...states].sort(), ['busy', 'idle', 'unknown', 'waiting']);
  const waiting = fleet.rows.filter((r) => stateOf(r) === 'waiting');
  assert.equal(waiting.length, 1);
  assert.equal(waiting[0].waitingFor, 'permission prompt', 'the caption under the waiting node');
});

// A `!` in a screenshot is a reading the reader is being told not to trust, and one that
// appeared because the demo's ages drifted is a mark the fleet never earned.
test('no reading in the captured minute is stale, so nothing in the screenshots is dated', () => {
  const fleet = fleetAt(DEMO_MINUTES - 1);
  assert.equal(fleet.health.stale, 0);
  for (const r of fleet.rows) {
    assert.ok(r.snapshotAgeMs !== null && r.snapshotAgeMs < DEFAULT_STALE_AFTER_MS, `${r.project} is dated`);
  }
});

// Every banner this page can raise is a real signal, so the captures may carry exactly the one
// their own fleet earns: a session reporting a status word tarmac does not know. The rest —
// coverage, drift, unreadable payloads, an unchecked Claude Code build — would be the demo
// misconfigured, showing a reader a failure that is not the product's.
test('the captured fleet earns one banner and no other', () => {
  const { rows, health } = fleetAt(DEMO_MINUTES - 1);
  assert.equal(health.unknownStatus, 1, 'the unknown node the README names, and only one');
  assert.equal(health.covered, health.sessions, 'every session chained: no coverage banner');
  assert.equal(health.schemaGuard.state, 'ok', 'a Claude Code build the fixtures cover: no shape-check footnote');
  assert.equal(health.noSessionId, 0);
  assert.equal(health.drift, 0);
  assert.equal(health.schemaBroken, false);
  assert.equal(busyOnStaleFleet(rows), 0);
});

// The span the scrubber says it covers is a day only because the demo plays one minute more
// than the ring holds: at 1440 exactly, nothing has aged out, `dropped` stays false, and
// `since` reverts to the moment the process started — a day AFTER the oldest sample it is
// serving. The record would then be lying in the one sentence the README quotes it for.
test('the demo plays one minute more than the ring keeps, so the record dates itself by its own oldest slot', () => {
  assert.equal(DEMO_MINUTES, HISTORY_SLOTS + 1);
});

// A session that has been recycled and has not spoken since: the key present, holding null,
// which the map draws as a dotted dial saying "no turn yet" rather than a ring at zero. It is
// the state this project exists to get right, and the replay walks past one because of this.
test('the day holds a session that has taken no turn yet, and it is not a zero', () => {
  const noTurnYet = [];
  for (let m = 0; m < DEMO_MINUTES; m++) {
    for (const r of fleetAt(m).rows) if (r.ctxState === 'fresh') noTurnYet.push({ m, project: r.project, pct: r.ctxPct });
  }
  assert.ok(noTurnYet.length > 0, 'no minute of the day has a session that has taken no turn');
  for (const { m, pct } of noTurnYet) assert.equal(pct, null, `minute ${m} reports a percentage for an unmeasured window`);
});

// The GIF's whole subject: the five-hour window filling, rolling over and filling again while
// the scrubber walks the day. A flat allowance would make a replay of it a still image.
test('the five-hour window fills and rolls over across the day', () => {
  const pcts: number[] = [];
  for (let m = 0; m < DEMO_MINUTES; m++) {
    const [fiveHour] = readLimits(fleetAt(m).rows[0].rateLimits, at(m));
    assert.notEqual(fiveHour.pct, null, `minute ${m} has no five-hour reading`);
    pcts.push(fiveHour.pct!);
  }
  const rollovers = pcts.filter((p, i) => i > 0 && p < pcts[i - 1] - 20).length;
  assert.ok(rollovers >= 3, `a day holds four or five windows, this one rolled over ${rollovers} times`);
  assert.ok(Math.max(...pcts) >= 70, 'no window ever gets full enough to be worth watching');
});

// The scrubber walks minutes, not sessions, so a minute with nobody in it is a frame of empty
// map with no explanation on it. `demoMinute(DEMO_MINUTES)` IS empty — every actor's `dies` is
// that minute — which is why the harness clamps what it publishes to the last minute of the
// day rather than trusting two timers to agree about when the day ended.
test('no minute of the day the harness plays is an empty fleet', () => {
  for (let m = 0; m < DEMO_MINUTES; m++) {
    assert.ok(fleetAt(m).rows.length > 0, `minute ${m} of the day has no sessions at all`);
  }
});

// A day that is the same fleet at every minute is a scrubber with nothing behind it.
test('the fleet changes across the day: sessions come and go, and states move', () => {
  const counts = [0, 400, 812, DEMO_MINUTES - 1].map((m) => fleetAt(m).rows.length);
  assert.ok(new Set(counts).size > 1, `the same ${counts[0]} sessions all day`);
  // Who is there and what each of them is doing, minute by minute. The GIF is a walk through
  // this list, so a day that holds two of them is a day worth two frames.
  const shapes = new Set<string>();
  for (let m = 0; m < DEMO_MINUTES; m += 7) {
    shapes.add(
      fleetAt(m)
        .rows.map((r) => `${r.project}:${stateOf(r)}`)
        .sort()
        .join(' '),
    );
  }
  assert.ok(shapes.size >= 8, `the whole day is ${shapes.size} distinct fleet(s)`);
});
