import { createDemoHistoryStore } from './src/demo-history.ts';
import { demoDayStart } from './src/demo.ts';
const NOW = new Date(2026, 7, 7, 12).getTime();
const s = createDemoHistoryStore({ dayStart: demoDayStart(NOW) });
let a = Date.now();
const w = await s.read('7d', NOW);
console.log('7d ms', Date.now() - a, 'days', w.days.length, 'lines', w.coverage.lines);
console.log('day totals', w.days.map(d => Math.round(d.byProject.reduce((x,p)=>x+p.costUsd,0)*100)/100));
a = Date.now();
const m = await s.read('30d', NOW);
console.log('30d ms', Date.now() - a, 'days', m.days.length);
